export const LOOKUP_WORD = 'LOOKUP_WORD'
export const SELECT_WORD = 'SELECT_WORD'

export const LOOKUP_SUGGESTIONS = 'LOOKUP_SUGGESTIONS'
export const CLEAR_SUGGESTIONS = 'CLEAR_SUGGESTIONS'

export const LOOKUP_CASES = 'LOOKUP_CASES'

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export const CHANGE_ROUTE = 'CHANGE_ROUTE'

export const START_LOADING = 'START_LOADING'
export const STOP_LOADING = 'STOP_LOADING'
